default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  host: localhost
  database: practice_app_development
  username: dev
  password: dev
  port: 5437
  <<: *default

test:
  host: localhost
  database: practice_app_test
  username: dev
  password: dev
  port: 5437
  <<: *default
production:
  <<: *default
  database: practice_app_production
  username: practice_app
  password: <%= ENV['PRACTICE_APP_DATABASE_PASSWORD'] %>
